*** Variables ***
${btn_open_form_login}    accessibility_id=Đăng nhập
${input_phone_number}   id=login_phone_number
${input_password}    id=login_password
${btn_nav_login}    id=btn_login
${lbl_chao_mung_user}    xpath=//android.widget.ImageView[contains(@content-desc, 'Chào mừng')]
${msg_loi_dang_nhap_sdt}    accessibility_id=Vui lòng nhập số điện thoại
${msg_loi_dang_nhap_mat_khau}    accessibility_id=Vui lòng nhập số điện thoại
