*** Variables ***
${btn_chon_hoa_don_chua_thanh_toan_coc}    xpath=//android.view.View[contains(@content-desc, 'Chưa thanh toán') and contains(@content-desc, 'Đặt cọc căn hộ')][1]
${btn_chon_hoa_don_chua_thanh_toan_tien_thue}    xpath=//android.view.View[contains(@content-desc, 'Chưa thanh toán') and contains(@content-desc, 'Hóa đơn tiền thuê')][1]
${btn_chon_hoa_don_chua_thanh_toan_tien_coc_giu_cho}    xpath=//android.view.View[contains(@content-desc, 'Chưa thanh toán') and contains(@content-desc, 'Cọc giữ chỗ')][1]
${btn_thanh_toan_phieu}    id=btn_pay_invoice
